module SkelText where

-- Haskell module generated by the BNF converter

import AbsText
import ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transIdent :: Ident -> Result
transIdent x = case x of
  Ident string -> failure x
transCommand :: Command -> Result
transCommand x = case x of
  IsIn eperson elocation -> failure x
  WhereIs eitem -> failure x
  HowMany eperson -> failure x
  WhereWasBefore eperson elocation -> failure x
  WhereWasAfter eperson elocation -> failure x
  HowDo elocation1 elocation2 -> failure x
  Either eperson elocation1 elocation2 -> failure x
  NoMore eperson elocation -> failure x
  Move eperson elocation -> failure x
  Take eperson eitem -> failure x
  Handed eperson1 eitem eperson2 -> failure x
  Give eperson eitem -> failure x
  IsOf elocation1 edirection elocation2 -> failure x
transELocation :: ELocation -> Result
transELocation x = case x of
  ELocation ident -> failure x
transEDirection :: EDirection -> Result
transEDirection x = case x of
  EWest -> failure x
  EEast -> failure x
  ENorth -> failure x
  ESouth -> failure x
transEItem :: EItem -> Result
transEItem x = case x of
  EItem ident -> failure x
transEPerson :: EPerson -> Result
transEPerson x = case x of
  EPerson ident -> failure x

